### ISSUE TITLE
What do you benchmark

### ISSUE THREAD

**Issue by fkrauthan** [tonyspiro/tonyspiro.com-react#2]
Another question. You claim its 10 times faster. But isn't the main difference that with react you async load the content (Not part of your benchmark) and render the site in the browser. While with wordpress it directly interacts with the database and does the processing not on runtime?

To have a real benchmark you would need to wait for the react version to complete render and stop that time. Or do I miss something here?

**Comment by tonyspiro** [comment]
You are correct.  It is 10x faster to "first paint".  This is the real benefit from the React / API set up, less server overhead and faster page load times between "pages" as well.

**Comment by fkrauthan** [comment]
You probably should state that on your page. Its kinda like comparing Apples with Bananas.

**Comment by tonyspiro** [comment]
Thanks for the suggestion, I've made the changes to the [README.md file](https://github.com/tonyspiro/tonyspiro.com-react/blob/master/README.md)
